#! /bin/sh

source $HOME/.config/bspwm/panel.cfg
hsetroot -fill /home/aaron/Pictures/Linux-Manjaro-_751603-46.jpg
xset +fp /usr/share/fonts
xset fp rehash
fc-cache
amixer set Master 0

bspc monitor -d term chat www

bspc config border_width        2
bspc config window_gap          5
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config top_padding         20
bspc config focus_follows_pointer true

$HOME/.config/bspwm/panel &
